import styled from "@emotion/styled";
export const Section = styled.section`  width: 600px;
  margin-left: auto;
  margin-right: auto;`;
export const Title = styled.h2` outline: 1px solid grey;
  text-align: center;`;
export const StatisticList = styled.ul`  list-style: none;
  display: flex;
  justify-content: center;`;
export const StatisticListItem = styled.li`  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 60px;
  width: 60px;`;
export const Label = styled.span` margin-bottom: 7px;
  font-size: 12px;
  color: #fafafa;`;
export const Percentage = styled.span`  font-size: 16px;
  font-weight: 400;
  color: #fafafa;`;